### PR TITLE
module03 completed / .gitignore completed

### LINKED ISSUE #17: Module_03

### PR DESCRIPTION
**Pull request by peterbikes**
- module 03 completed, further testing requested;
- .gitignore updated;

### CODE REVIEW

**Comment by Axel-ex** [comment]
The exercice is working well and the design is cool! My only suggestions are:
- implementing checks for phone number /  duplicated contact.
- Adding the possibility to save the current contact list / open it from an external source

**Comment by peterbikes** [comment]
GraphicPhonebook is now:
- Demanding first name;
- Forbidding duplicated contacts;
- Only digits on contacts;

.gitignore also updated

**Comment by Axel-ex** [comment]
You can use regex to make sure that the phone number was digits and is a of a certain length!
Everything 🆗

**Review by Axel-ex — COMMENTED** [review]
You can use regex to make sure that the phone number was digits and is a of a certain length!
Everything 🆗

**Review by Axel-ex — APPROVED** [review]
🆗

**Pull request merged**
